spring:
  application:
    name: consumer
server:
  port: 6999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
resilience4j.retry:
  retryAspectOrder: 399
  backends:
    retryBackendA:
      maxRetryAttempts: 3
      waitDuration: 600
      eventConsumerBufferSize: 1
      enableExponentialBackoff: false
      exponentialBackoffMultiplier: 2
      enableRandomizedWait: false
      randomizedWaitFactor: 2
#      retryExceptionPredicate: io.github.resilience4j.circuitbreaker.RecordFailurePredicate
#      retryExceptions:
#        - java.io.IOException
#      ignoreExceptions:
#        - io.github.resilience4j.circuitbreaker.IgnoredException