spring:
  application:
    name: consumer
server:
  port: 6999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
resilience4j.ratelimiter:
    limiters:
        backendA:
            limitForPeriod: 1
            limitRefreshPeriodInMillis: 2000
            timeoutInMillis: 2000
            subscribeForEvents: true
            registerHealthIndicator: true
            eventConsumerBufferSize: 100