spring:
  application:
    name: consumer
server:
  port: 6999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
#resilience4j.circuitbreaker:
#    backends:
#        backendA:
#            ringBufferSizeInClosedState: 5
#            ringBufferSizeInHalfOpenState: 3
#            waitInterval: 5000
#            failureRateThreshold: 50
#            eventConsumerBufferSize: 10
#            registerHealthIndicator: true
#            recordFailurePredicate: com.justdojava.consumer.RecordFailurePredicate
#            recordExceptions:
#                - org.springframework.web.client.HttpServerErrorException
#            ignoreExceptions:
#                - org.springframework.web.client.HttpClientErrorException