spring:
  application:
    name: consumer
server:
  port: 6999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
resilience4j.retry:
  retryAspectOrder: 399
  backends:
    retryBackendA:
      maxRetryAttempts: 3
      waitDuration: 1000
      eventConsumerBufferSize: 1
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 5
      enableRandomizedWait: false
      randomizedWaitFactor: 2
      retryExceptionPredicate: com.justdojava.consumer.RecordFailurePredicate
      retryExceptions:
        - java.io.IOException
      ignoreExceptions:
        - com.justdojava.consumer.IgnoredException